### ISSUE TITLE
Fatal Bug beim Speichern einer Seite mit show="fields"

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-cris#323]
Das Speichern eine Seite (und damit wahrscheinlich auch die Anzeige) einer Seite mit dem Shortcode 
[cris show="fields"]

liefert einen Fatal Error:

```
Array
(
    [level] => FATAL
    [message] => Uncaught TypeError: RRZE\Cris\Tools::field_filter(): Return value must be of type array, null returned in .../wp-content/plugins/fau-cris/includes/Tools.php:537
    [datetime] => 27-Nov-2024 15:55:36 UTC
    [details] => Array
        (
            [0] => Uncaught TypeError: RRZE\Cris\Tools::field_filter(): Return value must be of type array, null returned in .../wp-content/plugins/fau-cris/includes/Tools.php:537
            [1] => Stack trace:
            [2] => #0 .../wp-content/plugins/fau-cris/includes/Forschungsbereiche.php(199): RRZE\Cris\Tools::field_filter()
            [3] => #1 .../wp-content/plugins/fau-cris/includes/Forschungsbereiche.php(80): RRZE\Cris\Forschungsbereiche->fetch_fields()
            [4] => #2 .../wp-content/plugins/fau-cris/fau-cris.php(974): RRZE\Cris\Forschungsbereiche->fieldListe()
            [5] => #3 .../wp-includes/shortcodes.php(434): RRZE\Cris\FAU_CRIS::cris_shortcode()
            [6] => #4 [internal function]: do_shortcode_tag()
            [7] => #5 .../wp-includes/shortcodes.php(273): preg_replace_callback()
            [8] => #6 .../wp-includes/class-wp-hook.php(324): do_shortcode()
            [9] => #7 .../wp-includes/plugin.php(205): WP_Hook->apply_filters()
            [10] => #8 .../wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(1933): apply_filters()
            [11] => #9 .../wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(1018): WP_REST_Posts_Controller->prepare_item_for_response()
            [12] => #10 .../wp-includes/rest-api/class-wp-rest-server.php(1292): WP_REST_Posts_Controller->update_item()
            [13] => #11 .../wp-includes/rest-api/class-wp-rest-server.php(1125): WP_REST_Server->respond_to_request()
            [14] => #12 .../wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch()
            [15] => #13 .../wp-includes/rest-api.php(449): WP_REST_Server->serve_request()
            [16] => #14 .../wp-includes/class-wp-hook.php(324): rest_api_loaded()
            [17] => #15 .../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
            [18] => #16 .../wp-includes/plugin.php(565): WP_Hook->do_action()
            [19] => #17 .../wp-includes/class-wp.php(418): do_action_ref_array()
            [20] => #18 .../wp-includes/class-wp.php(813): WP->parse_request()
            [21] => #19 .../wp-includes/functions.php(1336): WP->main()
            [22] => #20 .../wp-blog-header.php(16): wp()
            [23] => #21 .../index.php(17): require('...')
            [24] => #22 {main}  thrown in .../wp-content/plugins/fau-cris/includes/Tools.php on line 537
        )

    [ocurrencies] => 14
)
```

**Comment by xwolfde** [comment]
Selber Fehler wird geworfen beim Versuch eine bereits gespeicherte Seite mit dem Shortcode show="equipment" zu bearbeiten

**Comment by xwolfde** [comment]
Ebenso Fatal Errors bei anderen Shortcodes:
<img width="1403" alt="grafik" src="https://github.com/user-attachments/assets/c36456d8-e585-4656-bb69-2f993a7e0edf">

**Comment by xwolfde** [comment]
Geht immer auf 
    [message] => Uncaught TypeError: RRZE\Cris\Tools::field_filter(): Return value must be of type array, null returned in .../wp-content/plugins/fau-cris/includes/Tools.php:537

zurück

**Comment by BastianMelsheimer** [comment]
Fixed in 3.23.2
